apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: config-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: config-demo
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 80