pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('Day-03-Jenkins-CICD/01-Basic-Application-CI-Pipeline') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir('Day-03-Jenkins-CICD/01-Basic-Application-CI-Pipeline') {
                    bat 'mvn test'
                }
            }
        }
    }

    post {
        always {
            junit 'Day-03-Jenkins-CICD/01-Basic-Application-CI-Pipeline/target/surefire-reports/*.xml'
        }

        success {
            echo 'Build and tests completed successfully!'
        }

        failure {
            echo 'Build or tests failed!'
        }
    }
}
