pipeline {

    agent any

    environment {
        IMAGE_NAME = "ai-notepad"
        IMAGE_TAG = "latest"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                bat 'mvn -f 01-Basic-Application-CI-Pipeline/pom.xml clean package -DskipTests'
            }
        }

        stage('Test') {
            steps {
                bat 'mvn -f 01-Basic-Application-CI-Pipeline/pom.xml test'
            }
        }

        stage('Docker Build') {
            steps {
                bat 'docker build -t %IMAGE_NAME%:%IMAGE_TAG% -f 03-Docker-Build-Push-Pipeline/Dockerfile .'
            }
        }

        stage('Docker Run') {
            steps {
                bat 'docker rm -f ai-notepad-container || exit /b 0'
                bat 'docker run -d --name ai-notepad-container -p 8080:8080 %IMAGE_NAME%:%IMAGE_TAG%'
            }
        }

    }

    post {
        success {
            echo 'Complete CI/CD pipeline successful!'
        }
    }
}