CREATE DATABASE IF NOT EXISTS dockerdb;

USE dockerdb;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

INSERT INTO users (name)
VALUES ('Initial User');