apiVersion: v1
kind: Service

metadata:
  name: backend-service
  namespace: production-demo

spec:
  type: ClusterIP

  selector:
    app: backend

  ports:

    - port: {{ .Values.backend.service.port }}

      targetPort: 80