pipeline {

    agent any

    environment {
        IMAGE_NAME = "ai-notepad"
    }

    stages {

        stage('Build') {
            steps {
                bat 'mvn -f 01-Basic-Application-CI-Pipeline/pom.xml clean package -DskipTests'
            }
        }

        stage('Build Image') {
            steps {
                bat 'docker build -t ai-notepad:latest -f 03-Docker-Build-Push-Pipeline/Dockerfile .'
            }
        }

        stage('Deploy') {
            steps {
                bat 'docker rm -f ai-notepad-container || exit /b 0'
                bat 'docker run -d --name ai-notepad-container -p 8080:8080 ai-notepad:latest'
            }
        }

    }

    post {

        failure {
            echo 'Deployment failed. Rollback required.'
            bat 'docker ps -a'
        }

    }
}